# Generated by Django 5.1.4 on 2026-02-18 14:37

import django.db.models.deletion
import participant_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('code', models.CharField(default=participant_auth.models.generate_participant_code, editable=False, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='company_session.group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='company_session.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'group'], name='participant_session_fe82ac_idx'), models.Index(fields=['code'], name='participant_code_902c4b_idx')],
            },
        ),
    ]
