# Generated by Django 5.1.4 on 2026-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'NO'), (0, 'NO_RESPONDE'), (1, 'SI')]),
        ),
    ]
