# Generated by Django 5.1.4 on 2026-02-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_uniq_card_canonical_version_and_more'),
        ('company_session', '0002_alter_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_current', to='cards.card'),
        ),
    ]
