# Generated by Django 5.1.4 on 2026-02-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_session', '0003_session_current_card'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='decks.deck'),
        ),
    ]
