# Generated by Django 5.1.4 on 2026-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='uniq_card_canonical_version',
        ),
        migrations.RemoveField(
            model_name='card',
            name='canonical_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='version',
        ),
    ]
